### ISSUE TITLE
Iguana / GLL as backend

### ISSUE THREAD

**Issue by nefanov** [nefanov/pathfinder#20]
Core module is a scratch solution and may be deprecated in future. We need an integration with another solvers as backends.
It could be implemented like there: https://github.com/JetBrains-Research/GLL4Graph

**Comment by nefanov** [comment]
http://iguana-parser.github.io

**Comment by pr0kuk** [comment]
As far as I understand, the GLL algorithm doesn't take a graph as input, but a path and looks for subpaths in it, so I did not understand how it can be connected to our task.

**Comment by nefanov** [comment]
> As far as I understand, the GLL algorithm doesn't take a graph as input, but a path and looks for subpaths in it, so I did not understand how it can be connected to our task.

Алексей, это может работать через обвязку, сделанную нашими Питерскими коллегами: https://github.com/JetBrains-Research/GLL4Graph

**Comment by nefanov** [comment]
Integrated already. Now performance tests should be provided.

**Comment by nefanov** [comment]
Completed by Ledneva Alexandra
