### ISSUE TITLE
Поддержка опции --thin-bb во фронтендах

### ISSUE THREAD

**Issue by nefanov** [nefanov/pathfinder#9]
**Is your feature request related to a problem? Please describe.**
Создаваемые в стандартных IR базовые блоки зачастую содержат очень много последовательной информации (что отражает смысл базового блока как участка программы, выполняемого последовательно, операция за операцией), при этом аггрегировать семантику, извлеченную из этой информации, в метку вершины (а затем и вх/вых рёбер), на практике  будет означать "извлечь ББ как частный случай". @pr0kuk @fasSstem 

**Describe the solution you'd like**
Предлагаю поддержать режим "разрезания" базовых блоков последовательно по операциям: так можно будет составлять из них паттерны для CFL-R, фильтруя непринципиальные операции и сущности, акцентируя внимание на отдельных последовательностях.

**Describe alternatives you've considered**
Не поддерживать --thin-bb, аггрегировать информацию скопом. Плюс-не надо ничего разрезать. Минус-нужен более "умный" лексер.

**Additional context**
Игрушечный пример для GCC-CFG, на коленке:
https://gist.github.com/nefanov/1f5dba40d96f07ed6fe797dddcec474c
Вот что мы имеем сейчас:
<img width="231" alt="graph.dot" src="https://user-images.githubusercontent.com/10009365/125210303-9f012400-e2a7-11eb-8a0d-1bdc969cbd70.png">

Так предпочтительно:
<img width="104" alt="res1.dot" src="https://user-images.githubusercontent.com/10009365/125210300-9dcff700-e2a7-11eb-97e9-f383ca251cec.png">

Нужно поддержать оба формата, для этого и нужна отдельная опция

**Comment by pr0kuk** [comment]
> Так предпочтительно:
> <img alt="res1.dot" width="104" src="https://user-images.githubusercontent.com/10009365/125210300-9dcff700-e2a7-11eb-97e9-f383ca251cec.png">

Нужно ли оставлять блоки состоящие только из названий (`<bb 2>`, `<bb 3>`) в таком представлении или их можно убрать?

**Comment by nefanov** [comment]
> > Так предпочтительно:
> > <img alt="res1.dot" width="104" src="https://user-images.githubusercontent.com/10009365/125210300-9dcff700-e2a7-11eb-97e9-f383ca251cec.png">
> 
> Нужно ли оставлять блоки состоящие только из названий (`<bb 2>`, `<bb 3>`) в таком представлении или их можно убрать?

Не обязательно, можно имя вершины наследовать, например, отдельным полем.
